export const CREATE_BLOG = 'CREATE_BLOG';
export const READ_BLOGS = 'READ_BLOGS';
export const READ_BLOG_BY_ID = 'READ_BLOG_BY_ID';
export const EDIT_BLOG_BY_ID = 'EDIT_BLOG_BY_ID';
export const DELETE_BLOG_BY_ID = 'DELETE_BLOG_BY_ID';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const READ_PROJECTS = 'READ_PROJECTS';
export const READ_PROJECT_BY_ID = 'READ_PROJECT_BY_ID';
export const EDIT_PROJECT_BY_ID = 'EDIT_PROJECT_BY_ID';
export const DELETE_PROJECT_BY_ID = 'DELETE_PROJECT_BY_ID';
